name: build

on:
  push:
    branches:
      - "master"
  pull_request:

concurrency:
  # Maximum of one running workflow per pull request source branch
  # or branch and run number combination (cancels old run if action is rerun)
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/loom-cache
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v2-

      - run: ./gradlew --no-daemon build
      - name: Upload build artifacts 1.12.2
        uses: actions/upload-artifact@v2
        with:
          name: 1.12.2
          path: versions/1.12.2/build/libs
      - name: Upload build artifacts 1.8.9
        uses: actions/upload-artifact@v2
        with:
          name: 1.8.9
          path: versions/1.8.9/build/libs
